# Pandas

In [1]:
# Importing Pandas

import pandas as pd

## Dataframe

- Data structure used represent tabular data in pandas.
- It also provides additional functionalities as well.
- Allows us to work with spreadsheets and other tables easily in python.

In [2]:
# Creating a dataframe

my_dataframe = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns=["A", "B", "C"], index=["X", "Y", "Z"])

print(my_dataframe)

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [3]:
# Display the first 5 rows

my_dataframe.head() # By default, it displays 5, but you can put the number of rows as an arg.

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [4]:
my_dataframe.head(1)

   A  B  C
X  1  2  3

In [5]:
# Display data from the bottom

my_dataframe.tail(1) # By default, loads the last 5 rows if no args are passed

   A  B  C
Z  7  8  9

In [6]:
# View the headers/columns

my_dataframe.columns

# Convert it to list for better view
my_dataframe.columns.tolist()

['A', 'B', 'C']

In [7]:
# The row labels are called index and we can view it as follows:

my_dataframe.index

# Convert it to list for better view
my_dataframe.index.tolist()

# By default the index and columns are labelled as numeric start from 0.

['X', 'Y', 'Z']

In [8]:
# View information of dataframe

my_dataframe.info()

<class 'pandas.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [9]:
# View meaningful stats of the dataframe

my_dataframe.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [10]:
# View the count of rows and columns of the dataframe

my_dataframe.shape

(3, 3)

In [11]:
# View total number of items

my_dataframe.size

9

## Loading data

In [9]:
coffee_data = pd.read_csv("sample_data/coffee.csv")

In [13]:
coffee_data.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

### Types of files to load

1. CSV - Easy to read even without loading.
2. Feather - Slightly smaller size than csv.
3. Parquet - Smaller size.

In [10]:
# Loading a parquet file
# Install pyarrow if you get import error.

results = pd.read_parquet("data/results.parquet")

In [15]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [16]:
results.columns.tolist()

['year',
 'type',
 'discipline',
 'event',
 'as',
 'athlete_id',
 'noc',
 'team',
 'place',
 'tied',
 'medal']

**Note**: Prefer `to_list()` for pandas and `tolist()` for numpy. Both are the same, it is just the convention.

In [17]:
olympics_data = pd.read_excel("data/olympics-data.xlsx")

In [18]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [19]:
# Importing a specific excel sheet from the workbook

olympics_results = pd.read_excel("data/olympics-data.xlsx", sheet_name="results")

In [20]:
olympics_results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

- It took much longer to read the excel file compared to reading a parquet file.
- CSV is the safest bet for most of the situations.
- It is a widely accepted file format.

### Exporting to files

- We can export the dataframe to files as well.

In [21]:
output_excel = coffee_data.to_excel("sample_data/coffee.xlsx")

### Working on Dataframes

In [22]:
# View the entire dataframe

print(coffee_data)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [23]:
# Better way

display(coffee_data)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [24]:
# Access random data

coffee_data.sample(3) # By defeault it returns single random row.

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
2     Tuesday    Espresso          30
10   Saturday    Espresso          45

In [16]:
# loc and iloc

'''
- They are two main ways to select rows and columns from a dataframe.
- loc is label based. We use index names and column names.
- iloc is position based. We use integer positions (0,1,2,3,4,...) like list indexing.
- The biggest difference is slicing.
'''

# Syntax
# coffee_data.loc[rows, columns]

coffee_data.loc[4] # Displays the data of the row index 4.

# For better view, coffee_data.loc[[4]]

Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object

In [34]:
coffee_data.loc[[0,2,3]] # Display the data of index 0, 2 and 3

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [35]:
coffee_data.loc[0:5] # Added slicing

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [36]:
# Grabbing the column along with the rows

coffee_data.loc[0:5, ["Day", "Units Sold"]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25

In [26]:
display(coffee_data)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [38]:
# Using iloc

coffee_data.iloc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [43]:
coffee_data.iloc[0:5, 2]

0    25
1    15
2    30
3    20
4    35
Name: Units Sold, dtype: int64

In [17]:
# Adding a square brackets makes a difference in the view
coffee_data.iloc[0:5, [2]]

   Units Sold
0          25
1          15
2          30
3          20
4          35

In [41]:
coffee_data.iloc[0:5, [0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [ ]:
# One of the difference to observe is that with loc the end index is inclusive. But with iloc, it is exclusive.
# iloc only works with indices for both rows and columns.

In [48]:
# Updating a specific value using loc

coffee_data.loc[1, "Units Sold"] = 69

display(coffee_data)

# We can update multiple values by slicing.

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          69
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [54]:
# We can also get specific values using at and iat
# Slicing won't work. Only single values.

print(coffee_data.at[0, "Units Sold"])

25

In [53]:
coffee_data.iat[0,0]

'Monday'

In [ ]:
# Another way to grab columns is just by using their names

coffee_data.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [56]:
coffee_data["Units Sold"]

0     25
1     69
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [57]:
# Sorting the values

coffee_data.sort_values("Units Sold", ascending=True) # Sorting in ascending order

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
11   Saturday       Latte          35
9      Friday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          69

In [58]:
coffee_data.sort_values("Units Sold", ascending=False) # Sorting in descending order

          Day Coffee Type  Units Sold
1      Monday       Latte          69
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
9      Friday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20

In [61]:
coffee_data.sort_index(ascending=False) # Sorting the indices in descending order

          Day Coffee Type  Units Sold
13     Sunday       Latte          35
12     Sunday    Espresso          45
11   Saturday       Latte          35
10   Saturday    Espresso          45
9      Friday       Latte          35
8      Friday    Espresso          45
7    Thursday       Latte          30
6    Thursday    Espresso          40
5   Wednesday       Latte          25
4   Wednesday    Espresso          35
3     Tuesday       Latte          20
2     Tuesday    Espresso          30
1      Monday       Latte          69
0      Monday    Espresso          25

In [ ]:
# Multi level sorting and filtering
coffee_data.sort_values(["Units Sold", "Coffee Type"], ascending=False)

# First sort by units sold. If there are two coffee types with the same value, then it will sort those as well.

          Day Coffee Type  Units Sold
1      Monday       Latte          69
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20

In [65]:
coffee_data.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

# This means sort the units sold in descending order and coffee type in ascending order

          Day Coffee Type  Units Sold
1      Monday       Latte          69
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20

## Filtering Data

In [22]:
# Loading the olympics data

bios = pd.read_csv("data/bios.csv")
noc_regions = pd.read_csv("data/noc_regions.csv")
results = pd.read_csv("data/results.csv")

In [67]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [69]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [81]:
# Find atheletes height greater than 200 cm

bios.loc[bios["height_cm"] > 200.00, ["name", "height_cm"]]

                      name  height_cm
1080        Bozhil Lozanov      208.0
1673      Alexis Rubalcaba      204.0
2647         Milan Šrejber      203.0
2827    Nik'oloz Deriugini      206.0
2832         Elşad Qadaşev      205.0
...                    ...        ...
143784  Daniel Miklasevich      203.0
143833  Garrett Muagututia      205.0
143834         Kyle Ensing      201.0
143835         Mitch Stahl      203.0
143919   Emerson Rodríguez      204.0

[1219 rows x 2 columns]

In [25]:
# We can even do the above thing without loc

bios[bios["height_cm"] > 200.00][["name", "height_cm"]]

                      name  height_cm
1080        Bozhil Lozanov      208.0
1673      Alexis Rubalcaba      204.0
2647         Milan Šrejber      203.0
2827    Nik'oloz Deriugini      206.0
2832         Elşad Qadaşev      205.0
...                    ...        ...
143784  Daniel Miklasevich      203.0
143833  Garrett Muagututia      205.0
143834         Kyle Ensing      201.0
143835         Mitch Stahl      203.0
143919   Emerson Rodríguez      204.0

[1219 rows x 2 columns]

In [40]:
# Adding more conditions
# Find the atheletes having height > 200 cm and born in UK.


bios.loc[(bios["height_cm"] > 200.00) & (bios["born_country"] == "GBR")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
36938,37233,Roger Brown,1968-07-04,Hexham,England,GBR,Great Britain,203.0,93.0,NaN
37065,37360,Peter Knapp,1949-10-27,London,England,GBR,Great Britain,201.0,94.0,NaN
37135,37430,Guy Pooley,1965-10-02,Watford,England,GBR,Great Britain,205.0,87.0,NaN
37180,37476,Gavin Stewart,1957-04-27,Belfast,Northern Ireland,GBR,Great Britain,205.0,100.0,NaN
40574,40883,Mike Staines,1949-05-30,Guildford,England,GBR,United States,201.0,91.0,NaN
46930,47279,Martin Harris,1969-05-21,Bow,England,GBR,Great Britain,201.0,92.0,NaN
53533,53913,Jack Budd,1899-03-16,Fulham,England,GBR,Great Britain,201.0,NaN,1952-03-16
57758,58166,Matthew Clempner,1956-05-20,Salford,England,GBR,Great Britain,205.0,100.0,NaN
63218,63688,George Skuodas,1970-08-16,Helensburgh,Scotland,GBR,Great Britain,203.0,120.0,NaN
68859,69376,Geoff Parsons,1964-08-14,Margate,England,GBR,Great Britain,203.0,79.0,NaN
68968,69485,Richard Slaney,1956-05-16,Redhill,England,GBR,Great Britain,201.0,120.0,NaN
91841,92572,Kieran West,1977-09-18,Kingston-upon-Thames,England,GBR,Great Britain,204.0,100.0,NaN
92108,92842,Mark Covell,1967-11-07,Glasgow,Scotland,GBR,Great Britain,201.0,130.0,NaN
111822,113068,David Price,1983-07-06,Liverpool,England,GBR,Great Britain,203.0,108.0,NaN
121014,122980,Ben Pipes,1986-10-21,Beverley,England,GBR,Great Britain,204.0,91.0,NaN
121042,123008,Robert Archibald,1980-03-29,Paisley,Scotland,GBR,Great Britain,211.0,113.0,2020-01-23
121043,123009,Eric Boateng,1985-11-20,Lambeth,England,GBR,Great Britain,208.0,113.0,NaN
121045,123011,Dan Clark,1988-09-16,Greenwich,England,GBR,Great Britain,210.0,110.0,NaN
121049,123015,Joel Freeland,1987-02-07,Farnham,England,GBR,Great Britain,208.0,111.0,NaN
121055,123021,Pops Mensah-Bonsu,1983-09-07,London,England,GBR,Great Britain,206.0,106.0,NaN
121060,123026,Drew Sullivan,1980-02-12,London,England,GBR,Great Britain,203.0,98.0,NaN
121258,123232,Moe Sbihi,1988-03-27,Kingston Hill,England,GBR,Great Britain,202.0,110.0,NaN
121724,123739,Liz Cambage,1991-08-18,Southwark,England,GBR,Australia,203.0,98.0,NaN
124035,126299,Kieron Achara,1983-07-03,Stirling,Scotland,GBR,Great Britain,208.0,110.0,NaN
124587,126895,Chris McDermott,1989-06-07,Birkenhead,England,GBR,Great Britain,204.0,105.0,NaN
124698,127021,Carl Myerscough,1979-10-21,Blackpool,England,GBR,Great Britain,208.0,160.0,NaN
124898,127239,Joe O'Regan,1991-06-22,Oldham,England,GBR,Great Britain,203.0,105.0,NaN
131275,134051,Paul Bennett,1988-12-16,Leeds,England,GBR,Great Britain,207.0,100.0,NaN
140298,143804,Aaron Geramipoor,1992-09-11,Stockport,England,GBR,Islamic Republic of Iran,214.0,NaN,NaN

In [ ]:
# Find atheletes whose name contains "Keith"

bios[bios["name"].str.contains("Keith")][["name", "born_country"]]

# Inside the contains, you can add a flag case=False, and then just search with "keith". It will give all possible "keith" variants.
# If you want to search for two names like keith or patrick, use .contains("keith|patrick"). It is a regex thing.

                        name born_country
1897            Keith Hanlon          NaN
3505           Keith Wallace          GBR
6228           Keith Hartley          CAN
8898             Keith Mwila          NaN
12053           Keith Hervey          GBR
...                      ...          ...
109900     Keith Cumberpatch          NZL
115973       Keith Sanderson          USA
117676          Duncan Keith          CAN
122121        Keith Ferguson          AUS
127310  Tracy Keith-Matchitt          NZL

[70 rows x 2 columns]

In [ ]:
# Filtering using isin
# Find atheles born in USA, France and Great Britain.

bios[bios["born_country"].isin(["USA", "FRA", "GBR"])][["name", "born_country"]]

                         name born_country
0       Jean-François Blanchy          FRA
1              Arnaud Boetsch          FRA
2                Jean Borotra          FRA
3             Jacques Brugnon          FRA
4                Albert Canet          GBR
...                       ...          ...
145454          Anna Hoffmann          USA
145457         Alix Wilkinson          USA
145467            Elisa Nakab          FRA
145468      Justin Abdelkader          USA
145498         André Foussard          FRA

[20576 rows x 2 columns]

In [ ]:
# In the couple of cells above, we can see that we are repeating bios again and again in the same statement to filter our meaningful data. We can reduce the repetition by using query.

bios.query("born_country == 'USA' and born_city == 'Seattle'")

# I don't see much options to filter the data using query. Our traditional way allowed us to drill down in a better way.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

## Adding and removing columns